- cmake/Modules/FindComputeCpp.cmake
This patch adds some licensing and documentation information for the
FindComputeCpp module in order to easily re-distribute the FindComputeCpp file
without the rest of the SDK.
> Adding documentation and license to FindComputeCpp

- cmake/Modules/FindComputeCpp.cmake
- samples/matrix_multiply/matrix_multiply.cpp
- Host matrix multiplication deals with non-divisible sizes of matrix
- SYCL variant only accepts power-of-two matrix sizes
- Error correction is added to both host and sycl variants
> Updating the matrix multiplication example

- cmake/Modules/FindComputeCpp.cmake
- samples/accessors/CMakeLists.txt
- samples/async_handler/CMakeLists.txt
- samples/custom_device_selector/CMakeLists.txt
- samples/example_sycl_application/CMakeLists.txt
- samples/gaussian_blur/CMakeLists.txt
- samples/hello_world/CMakeLists.txt
- samples/images/CMakeLists.txt
- samples/matrix_multiply/CMakeLists.txt
- samples/opencl_c_interop/CMakeLists.txt
- samples/parallel_for/CMakeLists.txt
- samples/reduction/CMakeLists.txt
- samples/simple_example_of_vectors/CMakeLists.txt
- samples/simple_local_barrier/CMakeLists.txt
- samples/simple_private_memory/CMakeLists.txt
- samples/simple_vector_add/CMakeLists.txt
- samples/smart_pointer/CMakeLists.txt
- samples/template_functor/CMakeLists.txt
- samples/using_functors/CMakeLists.txt
Fix #15
Supporting targets with multiple source files is a must-have feature for many projects.
> CMake target building from multiple TUs

- samples/opencl_c_interop/opencl_c_interop.cpp
- samples/simple_local_barrier/simple_local_barrier.cpp
`std::pow` and `std::iota` need to be declared before use
> Add missing headers preventing compilation on Ubuntu 16.10

- cmake/Modules/FindComputeCpp.cmake
Because it is fairly common that people do not set include directories for the given source folder, but on a per-target basis, I added the ability for the build scripts to detect such target properties and add them to the device compiler invocation. (plus fixed indentation on one line.)
> Added parsing of target include dirs

- .gitignore
- samples/hello_world/hello_world.cpp
Improve comments on hello_world sample and ignore the html/ folder where html documentation output is stored.
> Improve sample documentation and ignore html/

- .gitignore
- .travis.yml
- .travis/computecpp_workaround.sh
- README.asciidoc
- documents/ComputeCpp_Anatomy_Of_App.asciidoc
- documents/ComputeCpp_GettingStarted.asciidoc
- documents/ComputeCpp_Glossary.asciidoc
- documents/ComputeCpp_Integration_Guide.asciidoc
- documents/ComputeCpp_Overview.asciidoc
The vesion number has largely been removed from the repository, apart
from select places where a minimum version requirement has been
specified (like in the virtual pointer). The travis config needs a
more long-term, robust solution.
> Update the SDK with new ComputeCpp version

- utils/vptr/include/virtual_ptr.hpp
- utils/vptr/tests/accessor.cc
This pull request contains:
- a new template parameter for the allocator type to `get_buffer()`
- a test in accessor.cc
> Added a template parameter for allocator to `get_buffer()`

- utils/vptr/include/virtual_ptr.hpp
If the base address of the pointer mapper is 1, various tools will
complain about alignment, even though these are not "real" pointers.
Changing it to a user-specified variable, with a default highly-aligned
value, should fix this problem.
> Add user-specified base address to pointer mapper

- utils/vptr/include/virtual_ptr.hpp
- utils/vptr/tests/accessor.cc
The `detail` namespace should be avoided if possible.
> Use `buffer_allocator` instead of the `detail` allocators

- .travis.yml
- .travis/build_computecpp.sh
- .travis/computecpp_workaround.sh
- samples/example_vptr/CMakeLists.txt
Hopefully, this config will also not break when a new version is
released, as it now specifies the version of ComputeCpp to download.
> Update travis config for 0.3.2

- cmake/Modules/FindComputeCpp.cmake
- samples/using_functors/CMakeLists.txt
This CMake change allows the user to specify that their integration
headers should appear before after the main code of the source file.
This allows users to put enums in the template arguments of their
kernels, even though this is not stricly legal in SYCL code (but lots
of existing code does it).
This is not on by default, because it requires that all kernels used
*must* have a forward definition visible to the host compiler inside
the integration header. For example, you can't have a class local to
a function, or more specifically something like:
`cgh.parallel_for<class kernel_name>(range, [=]() { ... });`
This is an advanced property and is unlikely to be required by most
developers, but is there for the special cases.
> Add include-after CMake property

- include/vptr/virtual_ptr.hpp
This is a change we have in Eigen which allow to use the library with existing SYCL buffers.
So one can write
```
buffer<float, 1> buf(range<1>(10));
float* p = static_cast<float *>(static_cast<void *>(pMap.add_pointer(buf)));
```
and use p as if it were malloc'ed.
I'd like to make sure that this won't cause any issue.
> Allow to add existing buffer

- CMakeLists.txt
Hi,
I updated the CMakeLists.txt to change the order of the project command As specified at the documentation: https://cmake.org/cmake/help/latest/command/project.html
And I also updated the overwrite of CMAKE_MODULE_PATH, which is better to append, so you don't lose the current values.
Thanks
> CMakeLists.txt - minimum version before project command and append to CMAKE_MODULE_PATH

- include/vptr/virtual_ptr.hpp
- tests/vptr/basic.cc
The idea is to allow the user to remove pointers without reusing them.
It is particularly useful for sub-buffers because we don't want to keep their virtual pointer. With that it is possible to use Eigen with sub-buffers.
I am not too sure about the method name. Maybe it would make more sense to swap it with the existing remove_pointer (i.e. release_pointer allow to re-use the pointer but remove_pointer does not)?. I'll make sure Eigen synchronises with the latest changes we make here.
> Add method release_pointer to vptr

- .travis.yml
- .travis/build_computecpp.sh
- .travis/computecpp_workaround.sh
- samples/async-handler/async-handler.cpp
- samples/gaussian-blur/gaussian-blur.cpp
- samples/images/images.cpp
- samples/matrix-multiply/matrix-multiply.cpp
- samples/simple-private-memory/simple-private-memory.cpp
- samples/smart-pointer/smart-pointer.cpp
- samples/template-function-object/template-function-object.cpp
- samples/using-function-objects/using-function-objects.cpp
Some 1.2.1 features are missing and therefore are yet to change
(updates to the image normalisation flags for samplers for example).
> Update the SDK to ComputeCpp v0.5.0

- cmake/Modules/FindComputeCpp.cmake
This is a minimalist modification to enable building samples for Nvidia gpus (see issue #69 ).
To configure:
```bash
cmake -DCOMPUTECPP_USE_PTX=1 ..
```
> minimal modification to make samples work on Nvidia gpus

- cmake/Modules/FindComputeCpp.cmake
Previously the method of including the integration header after the user
source only worked for clang/gcc. It is possible to use a similar flag
on Windows, /TP, which indicates that all files should be compiled as
C++.
> Add include-after support to MSVC

- .travis.yml
- .travis/build_computecpp.sh
- .travis/computecpp_workaround.sh
- samples/images/images.cpp
- samples/ivka/ivka.cpp
- samples/opencl-c-interop/opencl-c-interop.cpp
- samples/simple-private-memory/simple-private-memory.cpp
More 1.2.1 changes have been integrated, though we're not 100% there
yet. Old code will continue to work but will show deprecation messages
(which I don't think are useful to see when building the SDK).
> Update SDK to ComputeCpp v0.5.1

- cmake/Modules/FindComputeCpp.cmake
When adding include directories it is easy to have the same include
directory linked to multiple cmake targets. Filter out any duplicate
include directories (and any other duplicate flags) before passing to
the compiler to keep the commands as terse as possible.
> Add step to remove any duplicate ComputeCpp flags

- samples/gaussian-blur/gaussian-blur.cpp
When MSVC captures a `constexpr` variable inside a lambda, it is no longer `constexpr` within the lambda. The solution is to make it `static constexpr`. This MR fixes the Gaussian blur test when using MSVC.
> Use `static constexpr` instead of `constexpr` (#95)

- samples/reinterpret/CMakeLists.txt
- samples/reinterpret/reinterpret.cpp
This new sample shows how the reinterpret buffer feature works. It
also shows a minor workaround required for the current version of
ComputeCpp related to dependency checking and reinterpreted buffers.
The sample shows how you can manipulate floating-point numbers as
though they are integers. Who knows, maybe your hardware doesn't
have an FP unit?
> Add new reinterpret buffer sample code

- include/vptr/README.adoc
- include/vptr/virtual_ptr.hpp
- tests/vptr/basic.cc
Fixes: https://github.com/codeplaysoftware/computecpp-sdk/issues/109
After discussing with @r-potter and Mehdi we think the best solution is to allow to malloc a 0 sized pointer and to free it without changing the map. Accessing this pointer throws an exception.
> Vptr: handle alloc zero

- cmake/Modules/FindComputeCpp.cmake
This fixes #112.
All but one sample are confirmed to still work on Windows after the change. The one that's not working is `vptr`, however, the same crash already occurred before the change. One additional caveat: Since I don't have a compatible GPU available on my Windows machine, I had to change the `gpu_selector` in `opencl-c-interop` to a `cpu_selector`.
This is also a necessary (but not sufficient) change in order to make the tests build on Windows again. I'll submit another PR for this in a minute.
Lastly, note that I had to roll back from ComputeCpp 0.8.0 to 0.7.0, since the former seems to have broken some of the samples (also on Linux).
> Fix const capture crash on Windows CMake builds

- .travis/build_computecpp.sh
- samples/images/images.cpp
- samples/simple-example-of-vectors/simple-example-of-vectors.cpp
- samples/simple-private-memory/simple-private-memory.cpp
The hierarchical samples now have the required h_item. Other samples
have had updates to their vector code, as single-element swizzles now
return 1-d vectors, not scalars, so require some coercing.
Additionally the travis config was slightly updated again, hopefully
to be even more robust with regards to the new ComputeCpp version.
> Update SDK to ComputeCpp v0.8.0

- .travis.yml
- .travis/before_install.sh
- CMakeLists.txt
Unfortunately we install an old version of CMake while travis appears
to have a nice new one preinstalled which we should use instead.
> Update Travis configuration

- .travis.yml
- .travis/before_install.sh
- .travis/build_computecpp.sh
- cmake/Modules/FindComputeCpp.cmake
Obviously, the Travis change. Slightly less obviously, the debug
build of ComputeCpp for Windows (which links against the debug CRT)
is missing from the package. If you are building on Windows, you
might get link errors for debug builds, or possibly even runtime
crashes. If you do run into any errors, please let us know. It will
be fixed in a subsequent release.
> Update SDK to ComputeCpp v0.9.0

- cmake/Modules/FindComputeCpp.cmake
Adds `DEPFILE` to the custom command that invokes the device compiler to
trigger rebuilds of the integration header once an included header changed when
using the Ninja generator and CMake 3.7 and up (as `DEPFILE` was only added in version 3.7).
This means that users stuck on CMake 3.6 and lower should still prefer the Makefile generator over the Ninja generator to avoid broken header dependencies.
The Ninja generator does not support `IMPLICIT_DEPENDS` (which is in turn supported by the Makefile generator). See [MR 66 on the Kitware Gitlab](https://gitlab.kitware.com/cmake/cmake/merge_requests/66). 
Additionally removes a trailing whitespace.
This variable may not be defined by the user if they set the CMake prefix instead (e. g. by using the `cmake_paths` generator in conan).
I tested …
> FindComputeCpp: Make `ComputeCpp_ROOT_DIR` optional, use depfiles 

- tools/makefile_basic/Makefile
Now that ComputeCpp ships with a `.pc` file the Makefile example should make use of that.
> Update makefile example for PkgConfig support

- cmake/Modules/FindComputeCpp.cmake
This is to support `target_link_libraries` with and without the `PRIVATE/PUBLIC/INTERFACE` keywords.
Closes #136.
> Replace target_link_libraries with set_property

- cmake/Modules/FindComputeCpp.cmake
This was causing issues if you installed ComputeCpp to a system
directory (like /usr). It was necessary in old code, but isn't
needed any more since we get all includes from the target that is
being compiled.
> Remove -isystem from device compiler command

- cmake/Modules/FindComputeCpp.cmake
Ninja has a problem if the name of the object doesn't match what it
expects, so this changes the generation to output a relative path, not
an absolute one. Additionally, the quotes in the optional DEPFILE
variable were causing problems, so they have also been removed.
> Update depfile generation for device compiler

- cmake/Modules/FindComputeCpp.cmake
Adds a CMake option `ComputeCpp_NATIVE_DIR`  that is used to specify the directory of the ComputeCpp package built for the native architecture. For example, when cross compiling for ARM on an x86 machine, `ComputeCpp_DIR` would point to the ARM package of ComputeCpp and `ComputeCpp_NATIVE_DIR` would point to the x86 one. This is required because the CMake script executes binaries from the ComputeCpp package.
> Simplify cross compilation with ComputeCpp_HOST_DIR

- .travis/build_computecpp.sh
- samples/reinterpret/reinterpret.cpp
The workaround for the reinterpret feature has been removed, as it
is no longer necessary.
> Update SDK to ComputeCpp v1.0.1

- cmake/Modules/FindComputeCpp.cmake
Rather than just adding the import ComputeCpp target, check to ensure
that the target doesn't already exist. This could happen if a single
cmake list ends up calling `find_package(ComputeCpp)` multiple times.
> Check if ComputeCpp target exists before adding

- include/vptr/virtual_ptr.hpp
The current behaviour of `get_node` in the virtual pointer mapper will
use `lower_bound` to get the buffer which is not less than the input
pointer. If the pointer mapper has only allocated one buffer, and we are
looking up a pointer offset into that buffer then the call to
`lower_bound` will return an iterator pointing past the end of the map.
This means we cannot dereference this iterator, as it does not point
into the map, but we still want to decrement this iterator to get the
buffer that the virtual pointer is referencing.
By adding a check for whether the iterator is the end we can short
circuit the iterator dereference, and so avoid this problem without
otherwise changing the behaviour of the pointer mapper.
> Add check so `end` iterator is not dereferenced

- include/vptr/virtual_ptr.hpp
The type `buffer_t` is defined in the class `PointerMapper` and is redefined to a different type in `get_buffer` which gives shadowing warnings.
`SYCLmalloc` doesn't have this issue but the alias should probably be changed for consistency.
The naming isn't great, renaming the first `buffer_t` to `buffer_mem_t` would make more sense but it is used in more places.
> Fix type shadowing

- include/vptr/virtual_ptr.hpp
- tests/vptr/accessor.cc
This PR fixes a test that was forgotten when travis broke, and adds a `parameter_list` argument to syclmalloc so that we can control allocation (e.g. `use_host_ptr`, `context_bound` etc).
> Fix accessor tests, and add property_list parameter to syclmalloc

- samples/builtin-kernel-example/CMakeLists.txt
- samples/builtin-kernel-example/builtin-kernel-example.cpp
This patch adds an example usage of the Codeplay extension CP018 (https://github.com/codeplaysoftware/standards-proposals/blob/master/builtin_kernels/index.md) , which will be part of the upcoming 1.0.3 release.
> Added initial example of builtin kernel

- cmake/Modules/FindComputeCpp.cmake
Added a thing to the makefile, let me know if there is a better way of doing this.
> Report an error when computecpp_info or compute++ can't be found (#126)

- samples/sync-handler/CMakeLists.txt
- samples/sync-handler/sync-handler.cpp
This example is specifically about a handler which fails to find a valid
device.
This should fix #105.
----
Once again, let me know if I'm not writing my code "sycl-y" enough, or you want another example with the CL context thing.
> Example of synchronous error handling

- cmake/Modules/ComputeCppCompilerChecks.cmake
- cmake/Modules/FindComputeCpp.cmake
Moving these compiler checks to a separate module keeps the main
FindComputeCpp.cmake clean and makes the checks "opt-in", if you
know that you won't need the check for your project.
@MathiasMagnus @ProGTX I'd appreciate if you could look at this!
Should fix #159
> Move compiler checks to separate module

- samples/placeholder-accessors/CMakeLists.txt
- samples/placeholder-accessors/placeholder-accessors.cpp
Probably not the best example, let me know if there is anything I should change/improve.
> Added a sample file demonstrating placeholder accessors (fixes #123)

- cmake/Modules/FindComputeCpp.cmake
Various changes mostly needed by Eigen:
- fix issue if multiple targets use the same source file
- ~take into account arguments from the `COMPILE_FLAGS` target property~ Removed as it may break the compiler if some flags are meant for a different host compiler only (i.e. gcc)
- call separate_arguments on `COMPUTECPP_USER_FLAGS` as the user should just be able to give space separated string
- remove unused `device_compiler_includes` variable
> Various CMake improvements

- cmake/Modules/FindComputeCpp.cmake
This allows to build a target using compute++ driver. For now CMAKE_CXX_COMPILER has to be set as late as possible (i.e just before calling add_sycl_to_target) otherwise CMake will reset the cache.
This doesn't affect any of the current samples in this repository.
I am not too sure about the variable naming convention. As far as I understand it we use camelCase for variable that are not exposed?
> Add support for compiler driver

- include/vptr/virtual_ptr.hpp
A pretty simple PR. This fixes some issues we have in the SYCL-BLAS when we include virutal_ptr.hpp across various files. Additionally, the file has been reformatted automatically in accordance with the computecpp-sdk clang-format style.
> Add header guards around virtual pointer, and format with clang-format

- samples/accessors/accessors.cpp
- samples/async-handler/async-handler.cpp
- samples/custom-device-selector/custom-device-selector.cpp
- samples/example-sycl-application/example-sycl-application.cpp
- samples/gaussian-blur/gaussian-blur.cpp
- samples/hello-world/hello-world.cpp
- samples/images/images.cpp
- samples/matrix-multiply/matrix-multiply.cpp
- samples/opencl-c-interop/opencl-c-interop.cpp
- samples/parallel-for/parallel-for.cpp
- samples/reduction/reduction.cpp
- samples/reinterpret/reinterpret.cpp
- samples/simple-example-of-vectors/simple-example-of-vectors.cpp
- samples/simple-local-barrier/simple-local-barrier.cpp
- samples/simple-private-memory/simple-private-memory.cpp
- samples/smart-pointer/smart-pointer.cpp
- samples/vptr/vptr.cpp
Some kernel names were not forward declarable, which is illegal in SYCL 1.2.1.
Add a forward declaration to those kernel name to make them globally visible.
> Fix non forward declarable SYCL kernel names

- samples/hello-world/hello-world.cpp
SYCL 1.2.1 does not require a queue to be waited upon its destruction leading to threads not have completed before the main thread finishes.
> Updated hello world sample to comply with the requirement that queues n SYCL 1.2.1 are not waited upon their destruction

- demos/README.md
Updates the build guide with a fix for building **Nbody** due to outdated dependency issue in `Cinder-ImGui`.
> Update build guide for demos

- samples/README.md
- samples/monte-carlo-pi.cpp
- samples/vptr.cpp
Includes a description of what all the samples do, separating SYCL basics from more "advanced" usage.
> Adding a README to /samples

- cmake/Modules/FindComputeCpp.cmake
It is unlikely that users will want to find compute++ on the path
with ComputeCpp libraries elsewhere in the system. By passing a
parameter to find_program in CMake, we stop it searching the PATH
and it will always instead find the ComputeCpp components in
system paths or the user-provided hint.
> Fix handling of $PATH in FindComputeCpp.cmake

- samples/reinterpret.cpp
SYCL kernel `item` parameter must be one-dimensional as we use
one-dimensional range as `parallel_for` argument.
Buffer accessor subscript operator is overloaded for `id` or `size_t`
types only.
Signed-off-by: Alexey Bader <alexey.bader@intel.com>
> Fix reinterpret sample bugs

- .travis.yml
It has been deprecated, and now does nothing.
> Remove sudo key from Travis config

- include/vptr/virtual_ptr.hpp
The vptr.hpp file used in the virtual pointer sample was using std::map but was missing <map> the header file <map>
I have added the <map> header to vptr.hpp to fix the compilation errors.
> Add missing header file <map> to virtual pointer sample

- .travis/build_computecpp.sh
- cmake/Modules/FindComputeCpp.cmake
- tests/CMakeLists.txt.in
The name of the ComputeCpp library has changed on Windows. Since
we are supporting MSVC 2019 now, we need to include the compiler
checks to make it work, and also need an update to Google Test
to avoid a deprecation in MSVC.
> Update SDK to ComputeCpp v2.0.0

- samples/monte-carlo-pi.cpp
Constant memory can be quite limited on some platforms and is better
used for small unchanging data that every work item might require.
Global memory fits the requirement better here.
> Remove constant memory from Monte Carlo sample

- samples/sync-handler.cpp
`std::any_of` requires `#include <algorithm>`.
Signed-off-by: Alexander Batashev <alexander.batashev@intel.com>
> Fix missing header in sync-handler sample

- cmake/Modules/ComputeCppCompilerChecks.cmake
- compute++ 2.1.0 is based on clang 8 and it can't parse the Windows headers for MSVC 19.27.
- This patch will make CMake try to build a simple program that includes cl/SYCL.hpp
- If the compilation fails we try to compile with __CUDACC__ and HAS_CONDITIONAL_EXPLICIT=0. If compute++ can build the file, those flags are added to COMPUTECPP_DEVICE_COMPILER_FLAGS
> Make CMake fail when compute++ can't compile code

- include/ivka/ivka.hpp
This only works if additional template parameters have default value,
and that value is used when passing type to is_accessor trait.
> Allow non-standard template parameters in accessor

- cmake/Modules/FindComputeCpp.cmake
ComputeCpp 2.2.1 provides support for SYCL 2020.
This patch exposes that by providing the `SYCL_LANGUAGE_VERSION` option.
Set for host and device compilers. Defaults to SYCL 1.2.1.
> SYCL_LANGUAGE_VERSION option

- README.md
- cmake/Modules/ComputeCppCompilerChecks.cmake
- cmake/Modules/ComputeCppIRMap.cmake
- cmake/Modules/FindComputeCpp.cmake
Adds support for setting multiple values in `COMPUTECPP_BITCODE`. When using ComputeCpp Professional Edition this allows multiple versions of the same kernel to be available in the same binary.
> Support for multiple bitcode targets in COMPUTECPP_BITCODE

- cmake/Modules/FindComputeCpp.cmake
Ran into problems with this where I was using the host_selector for my cl::sycl::queue, no warnings or issues came up at first. Then switched to default_selector which triggered some strange SYCL exceptions. Turns out it was caused by the fact that CMake will not warn the user if a passed string is empty or undefined. I was passing an empty string to add_sycl_to_target which was causing no sycl integration headers to be generated. This small change will print the following warning into the console when running CMake if no sources are provided:
```
CMake Warning at cmake/FindComputeCpp.cmake:403 (message):
No source files provided to add_sycl_to_target. SYCL integration 
headers may not be generated.
Call Stack (most recent call first):
CMakeLists.txt:63 (add_sycl_to_target)
```
> Add warning if no sources are passed to add_sycl_to_target

- samples/vector-addition-tiled.cpp
Using temporary static constexpr variable for local cause MSVC to fail. This PR removes the temporary to fix this issue.
> MSVC compiler error work around

- samples/vector-addition-examples.cpp
- samples/vector-addition-tiled.cpp
Seemingly MSVC cannot consume the constexpr constants in the
lambda without them being static as well.
> Fix usage of constexpr constants in MSVC

- cmake/Modules/FindComputeCpp.cmake
- samples/CMakeLists.txt
Instead of using `SDK_BUILD_IR`, `SDK_ADD_SYCL`, or `SDK_ADD_SAMPLE`
just use `ARG` since local variables are created anyway.
This should reduce the verbosity a bit.
> [CMake] ARG prefix for cmake_parse_arguments

- cmake/Modules/FindComputeCpp.cmake
1. Use multiple hints to find the ComputeCpp binaries
2. Removed unsupported `ComputeCpp_vs2015`
3. Updated copyright format to omit the date
> [CMake] Improved ComputeCpp discovery

- cmake/Modules/FindComputeCpp.cmake
Before, COMPUTECPP_BITCODE was set to a default of spir64. As we are aiming for SPIR-V to be the default this need to be changed. COMPUTECPP_BITCODE is now empty by default and when COMPUTECPP_BITCODE is empty, -sycl-target flag will not be used, letting the compiler decide whether to use SPIR or SPIR-V.
> Update COMPUTECPP_BITCODE to let compiler decide SPIR/SPIR-V by default

- include/vptr/README.md
- include/vptr/virtual_ptr.hpp
- samples/vptr.cpp
- tests/vptr/accessor.cc
- tests/vptr/basic.cc
- tests/vptr/offset.cc
- tests/vptr/space.cc
The vptr class is used in SYCL-BLAS. We want to be able to compile SYCL-BLAS using DPC++. The latest DPC++ nightlies generates errors due to the cl::sycl namespace used for virtual pointers. To avoid this issue, this patch uses the SYCL-2020 ::sycl namespace for DPC++.
> Change virtual pointer to use vptr namespace instead of cl::sycl::codeplay namespace

- samples/simple-example-of-vectors.cpp
Some misleading comments were removed, and types names updated to match the 2020 specification.
> Update vector sample to reflect better practice
